In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1, 3, 5, 7, 9], index = ['a', 'b', 'c', 'd', 'e'])
s

a    1
b    3
c    5
d    7
e    9
dtype: int64

In [6]:
data = {
    'index': ['a', 'b', 'c', 'd', 'e'],
    'std_id': [1, 3, 5, 7, 9],
    'department': ['Math', 'Physics', 'Chemistry', 'Biology', 'Computer Science']
}
df = pd.DataFrame(data)

In [7]:
display(df)

  index  std_id        department
0     a       1              Math
1     b       3           Physics
2     c       5         Chemistry
3     d       7           Biology
4     e       9  Computer Science

In [8]:
columns = ['index', 'student_id', 'departments']
df.columns = columns
display(df)

  index  student_id       departments
0     a           1              Math
1     b           3           Physics
2     c           5         Chemistry
3     d           7           Biology
4     e           9  Computer Science

In [ ]:
df[['index', 'departments','student_id']].dtypes

index          str
departments    str
dtype: object

In [10]:
df['student_id'] = df['student_id'].astype('category')
df[['index', 'departments','student_id']].dtypes

index               str
departments         str
student_id     category
dtype: object

In [11]:
df.tail(2)

  index student_id       departments
3     d          7           Biology
4     e          9  Computer Science

In [14]:
df.head(-1)

  index student_id departments
0     a          1        Math
1     b          3     Physics
2     c          5   Chemistry
3     d          7     Biology

In [15]:
print(df.head(-1))

  index student_id departments
0     a          1        Math
1     b          3     Physics
2     c          5   Chemistry
3     d          7     Biology

In [16]:
df.describe()

       index  student_id departments
count      5           5           5
unique     5           5           5
top        a           1        Math
freq       1           1           1

In [17]:
df.describe(include='category')

        student_id
count            5
unique           5
top              1
freq             1

In [20]:
df['student_id'].unique()

[1, 3, 5, 7, 9]
Categories (5, int64): [1, 3, 5, 7, 9]

In [ ]:
df['student_id'].nunique()

5

In [23]:
df['student_id'].idxmax()

4

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        5 non-null      str
 1   student_id   5 non-null      category
 2   departments  5 non-null      str
dtypes: category(1), str(2)
memory usage: 257.0 bytes

In [25]:
df['index'].sum

<bound method Series.sum of 0    a
1    b
2    c
3    d
4    e
Name: index, dtype: str>

In [26]:
x = df.values
type(x)

numpy.ndarray

In [27]:
display(df)

  index student_id       departments
0     a          1              Math
1     b          3           Physics
2     c          5         Chemistry
3     d          7           Biology
4     e          9  Computer Science

In [33]:
df.replace('Math','anas',inplace=True)
df

  index student_id       departments
0     a          1              anas
1     b          3           Physics
2     c          5         Chemistry
3     d          7           Biology
4     e          9  Computer Science

In [34]:
df.departments= df.departments.map(lambda x: x.upper())

In [35]:
df

  index student_id       departments
0     a          1              ANAS
1     b          3           PHYSICS
2     c          5         CHEMISTRY
3     d          7           BIOLOGY
4     e          9  COMPUTER SCIENCE